# cmake/PythonBuiltinModules.cmake
#
# 静态嵌入 CPython 时没有 .pyd 可加载,而 CPython 3.12 把 _socket / select /
# _queue 等一批 stdlib C 模块从核心拆成了独立扩展。这些模块必须编进
# Program.exe 并注册到 builtin import table,否则 import 直接失败。
#
# 用法:在 application/CMakeLists.txt 里 add_executable(Program ...) 之后
#       include(cmake/PythonBuiltinModules.cmake)
#
# 加一个扩展 = 下面加一个 ntvector_py_builtin(...) 调用 + 重编 exe。
# C++ 侧不用改:extern 声明和注册函数由本脚本生成到
#     ${CMAKE_BINARY_DIR}/generated/ntvector_python_builtin_inittab.inc
# 该文件被 application/Python/PythonRuntime.cpp include,其中生成的
# AppendStdlibInittab() 在 Py_Initialize() 之前调用。
#
# 注意:同一源文件被多次引用是安全的(如 pyexpat 与 _elementtree 共用 expat
# 的三个 .c),脚本会去重后只编译一次。

set(NTVECTOR_PY_SRC "${CMAKE_SOURCE_DIR}/third_party/Python-3.12.2")
set(_py_inittab_inc "${CMAKE_BINARY_DIR}/generated/ntvector_python_builtin_inittab.inc")

if(NOT TARGET Program)
    message(FATAL_ERROR "PythonBuiltinModules.cmake must be included after add_executable(Program ...)")
endif()

if(NOT (WIN32 AND MSVC))
    # 非 Windows/MSVC:PythonRuntime.cpp 仍会 include 这个 .inc,所以必须生成一个
    # 空的;真正的 stdlib C 扩展由动态链接的 CPython 自带(.pyd/.so),不编进 exe。
    file(GENERATE OUTPUT "${_py_inittab_inc}" CONTENT
"// AUTO-GENERATED by cmake/PythonBuiltinModules.cmake - DO NOT EDIT.
// 本平台非 Windows/MSVC:使用动态链接的 CPython,stdlib C 扩展来自其自带模块。

static void AppendStdlibInittab()
{
}
")
    target_include_directories(Program PRIVATE "${CMAKE_BINARY_DIR}/generated")
    return()
endif()

if(NOT EXISTS "${NTVECTOR_PY_SRC}/Modules/socketmodule.c")
    message(FATAL_ERROR
        "CPython source not found at ${NTVECTOR_PY_SRC}\n"
        "Expected a vendored Python-3.12.2 tree under third_party/.")
endif()

# expat 的三个实现文件,pyexpat 与 _elementtree 共用
set(_NTVECTOR_EXPAT_SRCS
    Modules/expat/xmlparse.c
    Modules/expat/xmlrole.c
    Modules/expat/xmltok.c
)

set(_NTV_PY_SOURCES "")
set(_NTV_PY_LIBS "")
set(_NTV_PY_INCDIRS "")
set(_NTV_PY_DECLS "")
set(_NTV_PY_CALLS "")

# ntvector_py_builtin(<模块名> <init 符号> [SOURCES ...] [DEFINES ...] [LIBS ...] [INCLUDES ...])
#   SOURCES / INCLUDES 均相对 CPython 源码树。
function(ntvector_py_builtin NAME INIT)
    cmake_parse_arguments(ARG "" "" "SOURCES;DEFINES;LIBS;INCLUDES" ${ARGN})

    if(NOT ARG_SOURCES)
        message(FATAL_ERROR "ntvector_py_builtin(${NAME}): SOURCES is required")
    endif()

    set(_srcs "")
    foreach(_s IN LISTS ARG_SOURCES)
        if(NOT EXISTS "${NTVECTOR_PY_SRC}/${_s}")
            message(FATAL_ERROR "ntvector_py_builtin(${NAME}): missing source ${_s}")
        endif()
        list(APPEND _srcs "${NTVECTOR_PY_SRC}/${_s}")
    endforeach()

    set(_incs "")
    foreach(_i IN LISTS ARG_INCLUDES)
        list(APPEND _incs "${NTVECTOR_PY_SRC}/${_i}")
    endforeach()

    # Py_BUILD_CORE_BUILTIN 是 CPython 对 builtin 扩展的标准宏,使 PyMODINIT_FUNC
    # 成为非 static 的导出符号。只加在这些扩展源文件上,不要污染 Program 的其
    # 他源文件(engine.cpp / pybind11 等都包含 Python.h)。
    # 这些宏会让 pyport.h 拉进 Include/internal/pycore_*.h,所以内部头目录也要
    # 只对这些源文件可见。
    foreach(_s IN LISTS _srcs)
        set_property(SOURCE "${_s}" APPEND PROPERTY
            COMPILE_DEFINITIONS Py_BUILD_CORE_BUILTIN _CRT_SECURE_NO_WARNINGS ${ARG_DEFINES})
        set_property(SOURCE "${_s}" APPEND PROPERTY
            INCLUDE_DIRECTORIES "${NTVECTOR_PY_SRC}/Include/internal")
    endforeach()

    set(_NTV_PY_SOURCES "${_NTV_PY_SOURCES};${_srcs}" PARENT_SCOPE)
    set(_NTV_PY_LIBS    "${_NTV_PY_LIBS};${ARG_LIBS}"       PARENT_SCOPE)
    set(_NTV_PY_INCDIRS "${_NTV_PY_INCDIRS};${_incs}"      PARENT_SCOPE)

    set(_decls "${_NTV_PY_DECLS}extern \"C\" PyObject* ${INIT}(void);\n")
    set(_calls "${_NTV_PY_CALLS}    PyImport_AppendInittab(\"${NAME}\", ${INIT});\n")
    set(_NTV_PY_DECLS "${_decls}" PARENT_SCOPE)
    set(_NTV_PY_CALLS "${_calls}" PARENT_SCOPE)
endfunction()

# ============================================================
# 模块表 — 加一行就多一个内置扩展
# ============================================================

# --- 框架与现有插件实际需要的 ---
ntvector_py_builtin(_socket  PyInit__socket
    SOURCES Modules/socketmodule.c
    LIBS    ws2_32 iphlpapi Rpcrt4)
ntvector_py_builtin(select   PyInit_select
    SOURCES Modules/selectmodule.c
    LIBS    ws2_32)
ntvector_py_builtin(_queue   PyInit__queue
    SOURCES Modules/_queuemodule.c)
# pythoncore 出于 zlib 符号冲突的考虑没有内建 zlib,这里对着项目自己的
# zlibstatic(application/include/zlib-1.3.1)编。
ntvector_py_builtin(zlib     PyInit_zlib
    SOURCES Modules/zlibmodule.c)

# --- 常见插件写法,源码都在 CPython 树内,无外部依赖 ---
ntvector_py_builtin(_hashlib   PyInit__hashlib
    SOURCES Modules/_hashopenssl.c)      # 用项目已静态链接的 OpenSSL
ntvector_py_builtin(unicodedata PyInit_unicodedata
    SOURCES Modules/unicodedata.c)       # unicodedata_db.h 随源码树提供
# 注意:winreg 不在这里 —— 它是核心内建(pythoncore.vcxproj 编 PC/winreg.c,
# PC/config.c 已注册),再注册一次会重复。
ntvector_py_builtin(_overlapped PyInit__overlapped
    SOURCES Modules/overlapped.c)
ntvector_py_builtin(_zoneinfo  PyInit__zoneinfo
    SOURCES Modules/_zoneinfo.c)
ntvector_py_builtin(winsound   PyInit_winsound
    SOURCES PC/winsound.c                # Windows 专属模块在 PC/ 下,不在 Modules/
    LIBS    winmm)
ntvector_py_builtin(_asyncio   PyInit__asyncio
    SOURCES Modules/_asynciomodule.c)
ntvector_py_builtin(_uuid      PyInit__uuid
    SOURCES Modules/_uuidmodule.c
    LIBS    rpcrt4)
ntvector_py_builtin(_multiprocessing PyInit__multiprocessing
    SOURCES Modules/_multiprocessing/multiprocessing.c
            Modules/_multiprocessing/semaphore.c
    INCLUDES Modules/_multiprocessing)
ntvector_py_builtin(pyexpat    PyInit_pyexpat
    SOURCES Modules/pyexpat.c ${_NTVECTOR_EXPAT_SRCS}
    DEFINES XML_STATIC
    INCLUDES Modules/expat)
ntvector_py_builtin(_elementtree PyInit__elementtree
    SOURCES Modules/_elementtree.c ${_NTVECTOR_EXPAT_SRCS}
    DEFINES XML_STATIC
    INCLUDES Modules/expat)

# ============================================================
# 应用到目标
# ============================================================

list(REMOVE_DUPLICATES _NTV_PY_SOURCES)
list(REMOVE_DUPLICATES _NTV_PY_LIBS)
list(REMOVE_DUPLICATES _NTV_PY_INCDIRS)

target_sources(Program PRIVATE ${_NTV_PY_SOURCES})
target_include_directories(Program PRIVATE ${_NTV_PY_INCDIRS})
target_link_libraries(Program PRIVATE ${_NTV_PY_LIBS})

# 生成注册代码。file(GENERATE) 只在内容变化时改写文件,避免每次 configure 都
# 让 PythonRuntime.cpp 白白重编。
file(GENERATE OUTPUT "${_py_inittab_inc}" CONTENT
"// AUTO-GENERATED by cmake/PythonBuiltinModules.cmake - DO NOT EDIT.
// 编进本 exe 的 stdlib C 扩展的声明与 builtin import table 注册。
// AppendStdlibInittab() 必须在 Py_Initialize() 之前调用。

${_NTV_PY_DECLS}
static void AppendStdlibInittab()
{
${_NTV_PY_CALLS}}
")
target_include_directories(Program PRIVATE "${CMAKE_BINARY_DIR}/generated")

string(REGEX MATCHALL "PyImport_AppendInittab" _ntv_py_appends "${_NTV_PY_CALLS}")
list(LENGTH _ntv_py_appends _ntv_py_mod_count)
list(LENGTH _NTV_PY_SOURCES _ntv_py_src_count)
message(STATUS "Python builtin extensions: ${_ntv_py_mod_count} modules / ${_ntv_py_src_count} sources -> ${_py_inittab_inc}")
